# Generated by Django 3.0 on 2019-12-11 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True)),
                ('view', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('seller_name', models.CharField(blank=True, max_length=20)),
                ('seller_number', models.CharField(blank=True, max_length=20)),
                ('place', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
