# Generated by Django 3.0 on 2019-12-11 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller_number',
            new_name='phone',
        ),
    ]
